- name: Remove bahmni-endtb-batch before installing
  yum:  name=bahmni-endtb-batch state=absent

- name: Install bahmni-endtb-batch
  yum:  name=http://bamboo.pih-emr.org/bahmni-repo/bahmni-endtb-batch-2.1.0-1.noarch.rpm state=present
